modules:
  acqui:
    lateorders:
      late_orders:
        -
          columnname: checkbox
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: order_date
        -
          columnname: estimated_delivery_date
        -
          columnname: vendor
        -
          columnname: information
        -
          columnname: total_cost
        -
          columnname: basket
        -
          columnname: basket_group
        -
          columnname: library
        -
          columnname: fund
        -
          columnname: claims_count
        -
          columnname: claimed_date

  admin:
    currency:
      currencies-table:
        -
          columnname: currency
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: rate
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: symbol
        -
          columnname: iso_code
          is_hidden: 1
        -
          columnname: last_updated
        -
          columnname: active
        -
          columnname: actions
