modules:
  module_name:
    page_name:
      table_id:
        -
          columnname: my_column_name
        -
          columnname: my_other_column_name
          cannot_be_toggled: 1
          cannot_be_modified: 1
