modules:
  acqui:
    lateorders:
      late_orders:
        -
          columnname: checkbox
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: order_date
        -
          columnname: estimated_delivery_date
        -
          columnname: vendor
        -
          columnname: information
        -
          columnname: total_cost
        -
          columnname: basket
        -
          columnname: basket_group
        -
          columnname: library
        -
          columnname: fund
        -
          columnname: claims_count
        -
          columnname: claimed_date

  admin:
    currency:
      currencies-table:
        -
          columnname: currency
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: rate
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: symbol
        -
          columnname: iso_code
          is_hidden: 1
        -
          columnname: last_updated
        -
          columnname: active
        -
          columnname: actions
  reports:
    lostitems:
      lostitems-table:
        -
          columnname: title
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: author
        -
          columnname: lostcode
        -
          columnname: barcode
        -
          columnname: callnumber
        -
          columnname: datelastseen
        -
          columnname: price
        -
          columnname: replacementprice
        -
          columnname: library
        -
          columnname: itemtype
        -
          columnname: current_location
        -
          columnname: location
        -
          columnname: notes
